pr: none

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: "ubuntu-latest"
  strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name estimagic python=$PYTHON_VERSION tox-conda -c conda-forge
    displayName: Create Anaconda environment

  - bash: |
      source activate estimagic
      tox

- job:
  displayName: Windows
  pool:
    vmImage: "windows-latest"
  strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - powershell: conda create --yes --quiet --name estimagic python=$PYTHON_VERSION tox-conda -c defaults -c conda-forge
    displayName: Create Anaconda environment

  - script: |
      call activate estimagic
      tox -e pytest