notifications:
    email: false

language: python

python: 3.6

env:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

# The tests run only if it is an PR or if a tag is pushed. This should prevent duplicate
# builds with pr and push. We cannot disable push as it also disables deployment via
# tags.
if: type != push OR tag IS present

install:
    # Install and configure conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a

    - conda install python=$PYTHON_VERSION

    - pip install tox-conda

script:
    - tox
