---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 50...100
  status:
    patch:
      default:
        target: 30%
    project:
      default:
        target: 90%
ignore:
  - .tox/**/*
  - release.py
  - setup.py
  - src/optimagic/benchmarking/cartis_roberts.py
  - src/optimagic/optimization/subsolvers/bntr_fast.py
  - src/optimagic/optimization/subsolvers/_trsbox_fast.py
  - src/optimagic/optimization/subsolvers/_conjugate_gradient_fast.py
  - src/optimagic/optimization/subsolvers/_steihaug_toint_fast.py
  - src/optimagic/optimization/subsolvers/gqtpar_fast.py
  - src/optimagic/optimization/tranquilo/clustering.py
  - tests/**/*
