name: estimagic

channels:
  - defaults
  - conda-forge

dependencies:

  - python=3.7
  - pip=19.0.3
  - pandas=0.24
  - numpy=1.16
  - pygmo=2.10
  - pip:
    - doc8
    - pre-commit
    - pytest
    - pytest-mock
    - pytest-xdist
    - restructuredtext_lint
    - tox-conda
