---
name: estimagic
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10  # dev
  - cyipopt<=1.2.0  # dev
  - jupyterlab  # dev, docs
  - nb_black  # dev, docs
  - nlopt  # dev, tests
  - pdbpp  # dev
  - pip  # dev, tests, docs
  - pytask>=0.0.11  # dev
  - pytest  # dev, tests
  - pytest-cov  # tests
  - pytest-xdist  # dev, tests
  - setuptools_scm  # dev
  - statsmodels  # dev, tests
  - toml  # dev
  - cloudpickle  # run, tests
  - joblib  # run, tests
  - numpy<2.0  # run, tests
  - pandas  # run, tests
  - plotly  # run, tests
  - pybaum >= 0.1.2  # run, tests
  - scipy>=1.2.1  # run, tests
  - sqlalchemy  # run, tests
  - myst-nb  # docs
  - sphinx  # docs
  - sphinx-copybutton  # docs
  - sphinx-design  # docs
  - sphinx-panels  # docs
  - sphinxcontrib-bibtex  # docs
  - tranquilo>=0.0.4  # dev, tests
  - seaborn  # dev, tests
  - mypy  # dev, tests
  - pip:  # dev, tests, docs
      - DFO-LS  # dev, tests
      - Py-BOBYQA  # dev, tests
      - black  # dev
      - blackcellmagic  # dev
      - fides==0.7.4  # dev, tests
      - gif  # dev
      - gif[matplotlib]  # dev
      - kaleido  # dev, tests
      - pre-commit  # dev
      - -e .  # dev
      # type stubs
      - pandas-stubs  # dev, tests
      - types-cffi  # dev, tests
      - types-openpyxl  # dev, tests
