name: estimagic

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip
  - anaconda-client
  - bokeh>=1.3
  - ansi2html
  - click
  - conda-build
  - conda-verify
  - fuzzywuzzy
  - joblib
  - jupyterlab
  - nbsphinx
  - pathos>=0.2.6
  - numdifftools>= 0.9.20
  - numpy=1.16
  - pandas>=0.24
  - pdbpp
  - petsc4py>=3.11
  - pygmo>=2.14
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy>=1.2.1
  - seaborn
  - sphinx=2.4.4
  - pydata-sphinx-theme>=0.3.0
  - sphinxcontrib-bibtex
  - sqlalchemy>=1.3
  - tox-conda
  - statsmodels
  - pip:
    - black
    - blackcellmagic
    - bump2version
    - pre-commit
