name: estimagic

channels:
  - conda-forge
  - defaults

dependencies:

  - python=3.7
  - pip=19.0.3
  - pandas=0.24
  - numpy=1.16
  - pygmo=2.10
  - conda-build
  - anaconda-client
  - numdifftools>= 0.9.20
  - bokeh>=1.3
  - scipy=1.2.1
  - conda-verify
  - sphinx
  - nbsphinx
  - numba >= 0.12
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - seaborn
  - jupyter
  - fuzzywuzzy
  - mpi
  - petsc4py>=3.11
  - sqlalchemy>=1.3
  - bump2version
  - pip:
    - pre-commit
    - pytest
    - pytest-mock
    - pytest-xdist
    - restructuredtext_lint
    - tox-conda
    - black
    - pdbpp
    - blackcellmagic
