{% set data = load_setup_py_data() %}

package:
  name: estimagic
  version: {{ data.get('version') }}

source:
  path: ../estimagic

build:
  number: 0
  entry_points:
    - estimagic = estimagic.cli:cli


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - click
    - joblib
    - numpy>=1.16.0
    - pandas>=0.24,<1.0
    - pygmo>=2.10
    - bokeh>=1.3
    - scipy
    - numdifftools>= 0.9.20
    - fuzzywuzzy
    - petsc4py>=3.11
    - numba
    - statsmodels>=0.9
    - sqlalchemy>=1.3

test:
  commands:
    - py.test
  source_files:
    - tox.ini
    - estimagic/tests
  requires:
    - pytest
    - pytest-mock

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  license: BSD
  license_file: LICENSE
  summary: Tools for the estimation of (structural) econometric models.
