[tool.nbqa.config]
isort = "setup.cfg"
black = "pyproject.toml"

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1


[tool.nbqa.addopts]
isort = ["--treat-comment-as-code", "# %%", "--profile=black"]
pyupgrade = ["--py36-plus"]


[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]


[tool.setuptools_scm]
write_to = "src/estimagic/_version.py"


[tool.pytask]
infer_latex_dependencies = true


[tool.ruff]
target-version = "py37"
select = ["ALL"]
fix = true
extend-ignore = [
    # Docstrings
    "D103", # missing docstring in public function
    "D107",
    "D203",
    "D212",
    "D213",
    "D402",
    "D413",
    "D415",
    "D416",
    "D417",
    # Others.
    "D404",  # Do not start module docstring with "This".
    "RET504",  # unnecessary variable assignment before return.
    "S101",  # raise errors for asserts.
    "B905",  # strict parameter for zip that was implemented in py310.
    "I",  # ignore isort

    "ANN101",  # type annotating self
    "ANN102",  # type annotating cls
    "FBT",  # flake8-boolean-trap
    "EM",  # flake8-errmsg
    "ANN401",  # flake8-annotate typing.Any
    "PD",  # pandas-vet
    "E731",  # do not assign a lambda expression, use a def

    # Things ignored during transition phase
    # ======================================
    "D",
    "ANN",
    "C901",  # function too complex
    "RET",
    "ISC",
    "BLE",
    # "RUF100", # unused noqa directive
    "ARG", # unused arguments
    "B904", # exception handling
    # ======================================
]


[tool.ruff.per-file-ignores]
"docs/source/conf.py" = ["E501", "ERA001", "DTZ005"]
"src/estimagic/parameters/kernel_transformations.py" = ["ARG001", "N806"]


[tool.ruff.pydocstyle]
convention = "numpy"
