name: estimagic_rtd

channels:

  - defaults
  - conda-forge
  - janosg

dependencies:
  - python=3.7
  - estimagic
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - jupyter
  - seaborn
  - patsy
