---
name: optimagic-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - typing-extensions
  - pip
  - setuptools_scm
  - toml
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - sphinx-design
  - sphinx-panels
  - ipython
  - ipython_genutils
  - myst-nb
  - furo
  - pybaum
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - patsy
  - joblib
  - plotly
  - pip:
      - ../
      - kaleido
      - Py-BOBYQA
      - DFO-LS
