name: mamba

# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'


jobs:

  run-tests-linux:

    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./environment.yml
          environment-name: estimagic
          cache-env: true
      - name: run pytest
        shell: bash -l {0}
        run: |
          micromamba activate estimagic
          pytest -m "not slow and not jax"
